### ISSUE TITLE
RGB mode is not working 

### ISSUE THREAD

**Issue by Jasmin92** [mauriliodc/thin_astra#4]
I followed all the instructions, the depth mode is working perfectly but I have a problem with the rgb mode. I don't get any color view, So I'm unable to get rgb images and use them.
Could you please tell me what's wrong? Thank you in advance.

**Comment by mauriliodc** [comment]
Are you using the Astra or the Astra Pro? (rgb is not accessible on the astra pro using openni2 right now)
Did you download the latest openni2 binaries/sources for the Astra?

**Comment by Jasmin92** [comment]
I'm using the Astra Pro, does this mean that it's impossible for me to use rgb right now?

**Comment by mauriliodc** [comment]
**Take this with a grain of salt**, since I did not use an Astro Pro since months.
As far as I know the Astra Pro has a different kind of RGB camera not accessible from the Openni2 framework BUT you can access it just like a normal camera/webcam (v4l2), the point is that there is now sync/registration out of the box.

**Comment by Jasmin92** [comment]
Thank you @mauriliodc ! I'll try to access it with the driver of a normal webcam.
